### ISSUE TITLE
Plugin breaks Panel of kirby v.3.4.0-rc.2

### ISSUE THREAD

**Issue by CrisGraphics** [gearsdigital/enhanced-toolbar-link-dialog#15] opened 2020-07-02 15:48 UTC
**Describe the bug**  
Unfortunately Your plugin breaks the panel of the recent kirby version.

**To Reproduce**  

Case 1:
1. If the panel is already installed, go to _panel/users_
2. No user is shown
3. Creating a new User also fails

**Console output**:
```
GET http://localhost/my-project/api/roles 500 (Internal Server Error)
message: "Call to a member function value() on string"

GET http://localhost/my-project/api/translations 500 (Internal Server Error)
message: Call to undefined method Kirby\Cms\Translation::title()
```
<img width="1538" alt="enhanced-toolbar-link001" src="https://user-images.githubusercontent.com/16305374/86379273-ef07dc80-bc8a-11ea-831f-4b83a8ae28d6.png">

Case 2:
1. Create a new kirby project
2. Go to _my-project/panel_
2. The panel installation page stays blank

**Console output**:
```
GET http://localhost/my-project/api/translations 500 (Internal Server Error)
message: Call to undefined method Kirby\Cms\Translation::title()
```

**enhanced-toolbar-link-dialog Version*  
1.2.3

**Kirby Version**  
3.4.0-rc.2

**Additional context**  
Many thanks in advance for having a look into it!  🙌🏼 😊

**Comment by gearsdigital** [comment] 2020-07-02 20:57
Hey @CrisGraphics, thank you so much for bringing is up 🤯

I can confirm this issue and need to have a deeper look. The changelog states a bunch of kirby refactorings so it probably relates to that. Not sure what is going on...

**Comment by CrisGraphics** [comment] 2020-07-03 06:44
Wish I could help You, but I (still) have absolutely no Vue skills, even though the issue seems to be php related...

**Comment by gearsdigital** [comment] 2020-07-03 07:37
I appreciate that but no worries! I already found the root cause but I’m still not sure why it breaks something totally unrelated 😑

I’m going to fix some of the other issues and provide a release soon.

**Comment by gearsdigital** [comment] 2020-07-03 20:50
@CrisGraphics This issue has now fixed. Sadly I'm not able to explain why this issue occurred at all. I'll try clariy that by opening a bug ticket in kirby core. It seems wired to me that something totally unrelated broken. I'll keep you updated here...

**Comment by CrisGraphics** [comment] 2020-07-06 08:04
Hey,
many thanks for looking into it, I really appreciate it.
Sadly it still doesn't work with kirby v3.4.0-rc2 (tried both installations, via composer and manually).

This is, what I get, when I want to install the panel:
<img width="1963" alt="starterkit-panel-install" src="https://user-images.githubusercontent.com/16305374/86568949-f28eb280-bf6d-11ea-8d70-3c6b23d92b7e.png">

And this, when a user already exists:
<img width="1960" alt="staterkit-panel-login" src="https://user-images.githubusercontent.com/16305374/86568978-0508ec00-bf6e-11ea-9a97-e9639dfd3074.png">

When I remove Your plugin from the plugins folder, everything works fine.
Not sure, what I'm missing here 🤔

**Comment by gearsdigital** [comment] 2020-07-06 09:14
@CrisGraphics Dang! Sorry for that... 🙊 Unfortunately I'm no longer able to reproduce this. Maybe it's a dumb question but have you tried to clear the browser cache?

![Bildschirmvideo aufnehmen 2020-07-06 um 11 08 25](https://user-images.githubusercontent.com/965069/86576964-cda03c80-bf79-11ea-8d80-9008f2c3f20b.gif)

It would be awesome if you could provide an example.

**Comment by CrisGraphics** [comment] 2020-07-06 10:34
Hm, that's weird,...
Here's how I installed it:

**Terminal**:

Installed the starterkit (as described [here](https://getkirby.com/docs/cookbook/setup/composer#starting-a-new-project)):
`composer create-project getkirby/starterkit starterkit`

then updated the require section of the `composer.json` to this:
```
"require": {
        "php": ">=7.1.0",
        "getkirby/cms": "dev-release/3.4.0",
        "gearsdigital/enhanced-toolbar-link-dialog": "^1.3"
    },
```
and then just hit
`composer update`

>   - Updating laminas/laminas-escaper (2.6.0 => 2.6.1): Downloading (100%)
- Updating filp/whoops (2.3.1 => 2.7.2): Downloading (100%)         
  - Updating phpmailer/phpmailer (v6.0.7 => v6.1.6): Downloading (100%)         
  - Updating claviska/simpleimage (3.3.3 => 3.3.4): Downloading (100%)         
  - Updating mustangostang/spyc (0.6.2 => 0.6.3): Downloading (100%)         
  - Removing getkirby/cms (3.3.6)
  - Installing getkirby/cms (dev-release/3.4.0 9fa1114): Cloning 9fa111493c from cache
  - Installing gearsdigital/enhanced-toolbar-link-dialog (v1.3.1): Downloading (100%) 

Cleared the browser cache and also tried it in another browser.

But,... no worries... I'll stick to kirby 3.3.6 for this project and give it another try, as soon as the stable version has been released :)
A trillion thanks again!

**Comment by janherman** [comment] 2020-07-07 14:46
I experience kind of similar issue after updating Kirby to 3.4.0 and Enhanced Toolbar Link Dialog to 1.3.1. When I open the panel, I get the error: Undefined index: type

**Comment by gearsdigital** [comment] 2020-07-07 16:08
Thank you very much @janherman for reporting this issue. I’ll have a look an try to investigate what is going on…

**Comment by gearsdigital** [comment] 2020-07-08 07:05
@janherman @CrisGraphics I reseted my kirby development environenment completely, installed a fresh starterkit and a the latest version of _Enhanced Toolbar Link Dialog_ (which is namly 1.3.1) via composer and for gods sake I've no issues :(

Could you please provide some details about your setup? What kind of other plugins have you installed?

**Comment by janherman** [comment] 2020-07-08 14:19
I think the issue is not related to other plugins. At least in my case. I tried fresh Kirby Starterkit, updated Kirby to 3.4.0 and installed the latest version of Enhanced Toolbar Link Dialog (1.3.1). Still get the same error. 

![Image 1](https://user-images.githubusercontent.com/22095056/86930020-ca9e7b00-c136-11ea-80d7-383c1cd7f81e.png)

I tested in latest Firefox and Chrome and I use Xampp with PHP 7.4.1 for development.

**Comment by gearsdigital** [comment] 2020-07-08 16:47
Thanks @janherman! Maybe this relates to PHP itself. You're using` 7.4.1` while I'm on [7.2.2](url). @CrisGraphics Which PHP Version are you running?

**Comment by gearsdigital** [comment] 2020-07-08 18:02
@janherman @CrisGraphics Could you please try to remove `'type'=> null,` from [`site/plugins/enhanced-toolbar-link-dialog/index.php:11`](https://github.com/gearsdigital/enhanced-toolbar-link-dialog/blob/master/index.php#L11) manually and tell me if that solves the issue?

**Comment by janherman** [comment] 2020-07-09 06:29
Thanks for your suggestion, @gearsdigital. I removed the line but it did not solve the issue. I even do not get to the login screen, the error message appears as soon as I try to access panel/login page (I was able to login before, the error message showed right after I logged in).

By PHP log you mean something like phpinfo() output or anything else?

**Comment by CrisGraphics** [comment] 2020-07-09 06:34
@gearsdigital Sorry for the late reply,
as @janherman mentioned, the error persists by removing the line. If I give the type some value, I can at least fill in the login form but after hitting login, the same error shows up again: `undefined index type`.
I'm also running php 7.4

**Comment by gearsdigital** [comment] 2020-07-09 06:40
I mean... WTF?

@janherman Just the php-error.log. You can lookup the location using `<?php phpinfo(); ?>`.
@CrisGraphics No worries. I'm glad you both are helping me out here :)

**Comment by CrisGraphics** [comment] 2020-07-09 06:44
Unfotunately there's still no docs for [custom models](https://getkirby.com/docs/reference/plugins/extensions/api#custom-models)...  Will try and look through Your code, maybe I'll find sth... 🙌🏼

**Comment by janherman** [comment] 2020-07-09 07:12
@gearsdigital Ok, I found it and there are no errors at all. :shrug:

**Comment by gearsdigital** [comment] 2020-07-09 07:13
Thanks for your effort!

**Comment by CrisGraphics** [comment] 2020-07-09 08:22
So, I don't know why, but I think I got it...
You also have to declare a type for the `simplepagecollection`:

```
'collections' => [
            'simplepagecollection' => [
              'type'=> null,
              'model' => 'simplepagemodel',
            ],
        ],
```

**Comment by gearsdigital** [comment] 2020-07-09 08:26
On step by the time. I'm now able tp reproduce this issue by adding `error_reporting(E_ALL);` to the top of the index.php. Now I only need to understand how custom models are really working.

**Comment by gearsdigital** [comment] 2020-07-09 08:32
@CrisGraphics I tried that biut it didn't work. I got it working by additionally adding `'type'=> null` to the models section. 

```diff
Kirby::plugin('gearsdigital/enhanced-toolbar-link-dialog', [
    'api'          => [
        'models'      => [
            // a camelCased model name results in Kirby\Exception\NotFoundException
            'simplepagemodel' => [
++            'type'=> null,
                'fields' => [
                    'id'    => function ($page) {
                        return $page->id();
                    },
                    'title' => function ($page) {
                        $query = option('gearsdigital.enhanced-toolbar-link-dialog.link.title', '{{ page.title }}');
                        return Str::template($query, [
                            'page' => $page,
                            'site' => site(),
                            'kirby' => kirby(),
                        ]);
                    },
                    'slug'  => function ($page) {
                        return URL::makeAbsolute($page->parent().DS.$page->slug());
                    },
                ],
            ],
        ],
        'collections' => [
            'simplepagecollection' => [
++           'type'=> null,
                'model' => 'simplepagemodel',
            ],
        ],
        'routes'      => [
            [
                'pattern' => 'enhanced-toolbar-link-dialog/pages',
                'method'  => 'get',
                'action'  => function () {
                    $page = get('page');
                    $query = get('search');

                    if (empty($query)) {
                        $query = '*';
                    }

                    $pagedCollection = site()->search($query, 'title')->paginate([
                        'page'  => $page,
                        'limit' => 10,
                    ]);

                    return $this->collection('simplepagecollection', $pagedCollection);
                },
            ],
        ],
    ],
    'translations' => [
        'en' => [
            'gearsdigital.enhanced-toolbar-link-dialog.internal' => 'Internal Link',
            'gearsdigital.enhanced-toolbar-link-dialog.external' => 'External Link',
            'gearsdigital.enhanced-toolbar-link-dialog.empty'    => 'No pages found',
            'gearsdigital.enhanced-toolbar-link-dialog.target.title' => 'Link Target',
            'gearsdigital.enhanced-toolbar-link-dialog.target.help' => 'Specify where to open the linked document.'
        ],
        'de' => [
            'gearsdigital.enhanced-toolbar-link-dialog.internal' => 'Interner Link',
            'gearsdigital.enhanced-toolbar-link-dialog.external' => 'Externer Link',
            'gearsdigital.enhanced-toolbar-link-dialog.empty'    => 'Keine Seiten gefunden.',
            'gearsdigital.enhanced-toolbar-link-dialog.target.title' => 'Link Ziel',
            'gearsdigital.enhanced-toolbar-link-dialog.target.help' => 'Gibt an, wo das verknüpfte Dokument geöffnet werden soll.',
        ],
    ],
]);

```

**Comment by CrisGraphics** [comment] 2020-07-09 08:33
Yes, that's exactly what I wrote above =)

**Comment by gearsdigital** [comment] 2020-07-09 08:35
My bad 🙈

I'ld love to have you as contributer here! https://opensource.com/article/19/7/create-pull-request-github

**Comment by gearsdigital** [comment] 2020-07-09 08:35
@janherman Can you verify the solution works for you?

**Comment by CrisGraphics** [comment] 2020-07-09 08:37
Thanks for the Tutorial Page (*embarrassed).
I'll check it out in a minute 😀

**Comment by janherman** [comment] 2020-07-09 08:39
Yes, I can confirm this solution works with my setup. 👍

**Comment by gearsdigital** [comment] 2020-07-09 08:41
Sorry, I didn't mean to embarrass you @CrisGraphics! I assumed that you're not familiar with making pull requests... If you have any questions please let me know. I'll guide you throug the process if you want to. Just want to make sure you get the credits here :)

**Comment by gearsdigital** [comment] 2020-07-09 08:43
@janherman Awesome! Thanks for checking out.

I'll provide a fix as soon as @CrisGraphics made the PR (No pressure @CrisGraphics. Take your time! ☺️ )

**Comment by CrisGraphics** [comment] 2020-07-09 09:42
> I assumed that you're not familiar with making pull requests...

You were assuming right, haha. Ok, I tried to make a pull request. Hope I didn't blow up GitHub or the Internet now...

**Comment by gearsdigital** [comment] 2020-07-09 10:54
How awesome :)

**Comment by gearsdigital** [comment] 2020-07-09 10:56
Thank you very much @janherman and @CrisGraphics! As this issue seems to be resolved now I'm going to close it :)

**Closed by gearsdigital** 2020-07-09 10:56 UTC
Labels: bug 🐞
