### ISSUE TITLE
Make search case-insensitive?

### ISSUE THREAD

**Issue by janherman** [gearsdigital/enhanced-toolbar-link-dialog#5] opened 2020-01-22 15:06 UTC
I just realized the search is case sensitive. For example, I have a page called "Kontakt". It does not find that page when I type "kontakt" into the search field. Is it possible to make it case-insensitive? :-)

**Comment by gearsdigital** [comment] 2020-01-22 15:24
Makes total sense! Thank you very much for reporting!

**Comment by gearsdigital** [comment] 2020-01-22 19:40
@janherman I was not able to reproduce this... 🧐

<img width="1110" alt="Bildschirmfoto 2020-01-22 um 20 38 52" src="https://user-images.githubusercontent.com/965069/72927919-5f631700-3d57-11ea-8e6b-e71066c8a70f.png">

**Comment by janherman** [comment] 2020-01-23 07:42
Ok, I have tested it again. :blush:

My first language is Czech. In Czech, there are some letters with diacritic. If a word starts with one of those letters, the search result is shown only after I finish the whole word. In other cases, I only start typing and the results filter accordingly.

**What I did:**
1. I have a page called "Školní jídelna"
2. Start typing "škol", nothing happens
3. Finish typing "školní jídelna", the page shows in search results
Just two screenshots to illustrate that. Start typing, nothing is shown:
![search-4](https://user-images.githubusercontent.com/22095056/72964561-8b63b400-3dba-11ea-9589-17f436036669.png)
Finish typing:
![search-5](https://user-images.githubusercontent.com/22095056/72964581-93bbef00-3dba-11ea-9555-3332f1d25a35.png)
4. Try searching again, this time starting with capital letter - "Škol" - result is shown immediately

I hope it makes sense. :smiley:

**Comment by gearsdigital** [comment] 2020-01-23 08:49
Thank you very much! Your explanation was awseome and I was now able to reproduce this issue.

I figured that this issue is not related to _Enhanced Toolbar Link Dialog_ to Kirby itself. Pretty sure this is somehow related to the underlying search enginge as this beaviour is also reproducable using the global search in the top right corner.

I filed an issue for Kirby and add a refernce to this issue: https://github.com/getkirby/kirby/issues/2408

Let's see what they say.

**Comment by gearsdigital** [comment] 2020-01-24 22:34
@janherman I'll close this issue for because the root cause is Kirby's underlying search. You can keep track of your issue in above mentioned Kirby issue.

Let me know if you find anything else or if you've ideas to improve this plugin.

**Closed by gearsdigital** 2020-01-24 22:34 UTC
Labels: bug 🐞
